### ISSUE TITLE
Headless: SearchBox isLoading is false when loading suggestions

### ISSUE THREAD

**Issue by tcarrio** [coveo/ui-kit#1012]
## Environment

This was encountered using `@coveo/headless@1.6.3`

## Description

Using a search box and subscribing to state updates, when updating the text it seems that the `isLoading` state property is never set to true as you would expect while fetching new suggestions for the latest text. This has been confirmed through debugging with a simple use case, with logs copied in the below screenshot.

There are two emitted values for every `updateText()` call. You can also see that for the first value, `suggestions` remain as they were previously, `isLoading` is `false`, and the network request is still in progress. After this, the fetch resolves. The second value is emitted, with the new `suggestions` with `isLoading` set to `false` as expected.

## Expectation

When a network request for query suggestions based on the updated text is in transit, `isLoading` should be `true`.

## Logs:

![image](https://user-images.githubusercontent.com/8659099/127363356-b77f1dc8-5cd6-45e8-b437-a36db61962be.png)

**Comment by olamothe** [comment]
Hi !

This is currently working "as designed" as the current `isLoading` property is meant to determine/inform that a "full search" request is in progress.

The original intention behind that state property was to allow developers to display some loading animation/UX feedback near or around the search input when the end user submits a query.

For query suggestions, since they typically return fast from the Coveo platform, it was originally deemed un-necessary to provide such "helper" state property.

Since changing the current behaviour of the `isLoading` property to take query suggestions request into account would be a breaking change, this is not something that we could change in the current major version.

We could add a new `querySuggestionsLoading` (or similar name) state property pretty easily.

However, I am interested in understanding the use case behind your request before doing any such change.
Could you provide some details ?

Thank you !

**Comment by tcarrio** [comment]
Hey @olamothe :wave:  thanks for getting back to me on this :grin: 

In our case we aren't interested in showing query suggestions for blank queries, instead we have a series of trending and recent searches that we show instead (Screen X). When simply showing suggestions when the input is a non-empty string (Screen Qx), we will see the previous query suggestions until the network request resolves and the suggestions update. This causes the screens to jump heavily when transitioning from the prior Q1 query suggestions to Q2.

Reverting to an empty input will show Screen X again, with the series of trending and recent search suggestions. This can be the third query or later, with the initial suggestions for `""`, then typing `"s"`, then backspacing to `""`.

Take the scenario such that query Q5 = `"s"`, Q6 = `""` (the user backspaces), and Q7 = "d". When transitioning from Q6 to Q7, the screens transition between X, then Q6, then Q7, where Q6 suggestions are shown until the network request resolves the new suggestions for Q7. This happens quickly, which is also why the experience is jarring.

Since it's impacting our user experience, it's not as much of "helper" state property but rather an actionable property for our frontend. With the presence of a `querySuggestionsLoading`, it is trivial for us to determine that the results shouldn't be shown for this scenario. We had originally done this using `isLoading` which is why we came across this in the first place.

**Comment by samisayegh** [comment]
Hi Tom, I opened a PR following this. It adds `isLoadingSuggestions` property to the search box controller's state.
