### ISSUE TITLE
Coveo Headless -  Pager vs QuerySummary - mismatch in total number of results

### ISSUE THREAD

**Issue by pauloguerraf** [coveo/ui-kit#2210]
hi,

I am implementing a search interface using coveo headless and react. After using both, the Pager and QuerySummary components to provide information about the results, I noticed the Pager shows a maxPage of **1000** with **5** results per page which should result in a total number of **5000** results, if I am not mistaken. Nevertheless, the QuerySummary total shows **357201** as the total number of results available. 

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1149371/178354133-436f48db-ae8e-426b-b07f-07e516a58899.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1149371/178354183-29cacee5-8440-4e0c-acbe-5a5b36f9e4b6.png">

this issue can be found on the documentation example hosted in codesanbox as well
[https://codesandbox.io/s/github/coveo/headless-documentation-material-ui-react-codesandbox/tree/version-1.77.9/?from-embed=&file=/src/App.tsx](https://codesandbox.io/s/github/coveo/headless-documentation-material-ui-react-codesandbox/tree/version-1.77.9/?from-embed=&file=/src/App.tsx) 

Also, the last page seems to work differently depending on the number of results shown per page. With 3 results per page no results are return when selecting the last page, seems there is an error in how maxPage is calculated.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1149371/178364192-59ca19bf-1ea2-46a4-9cdb-8be4e9e6b4c9.png">

thank you in advance for your help.

paulo

**Comment by olamothe** [comment]
Hello,

The difference between the maximum page you can reach in the result set (ie: using pagination) VS the total amount of possible results available in the index for a given query (ie: using query summary) is an index limitation.

There is a hard limit that you cannot go hover. It will typically vary between 1000 to 5000, depending on internal index configuration. This limit exists for performance reasons.

If the index allowed to load all results for any query (which could very well be multiple millions results in some cases), it would have to evaluate the relevancy of those millions of results in order to rank them all.

By adding an hard limit, it allows to return results in a more timely manner. So the query summary number is correct (there is 357201 possible results matching the query), the index just stops ordering them after 5000.

As for the problem with 1 VS 3 vs 5 results per page that you pointed out, it does indeed look like a bug.

Thanks for reporting !
